### PR TITLE
Update DirectPostAuthorizeResponse.php

### PR DESCRIPTION
**Pull request by joshbenham**
An update to @funju47shin pull request.

### CODE REVIEW

**Comment by sudiptpa** [comment]
:+1:

**Comment by delatbabel** [comment]
Should be a fix for #5

**Comment by delatbabel** [comment]
Please confirm that this works in production then I will tag for release.

**Comment by joshbenham** [comment]
Thanks @delatbabel. Give me a week to get back to you. Work is a bit crazy.

**Comment by sudiptpa** [comment]
@delatbabel @joshbenham  tested with the master branch in my machine it works fine, received Approved transaction with   sandbox credentials.

**Comment by joshbenham** [comment]
@delatbabel  yep this worked for us. Any chance of a tagged release so we can use composer again?

**Comment by delatbabel** [comment]
Tagged as v2.1.1

**Comment by sudiptpa** [comment]
@delatbabel Awesome !

**Pull request merged**
