### PR TITLE
Update DirectPostAuthorizeRequest.php

### PR DESCRIPTION
**Pull request by funju47shin**
When it redirects, it says to send card data, so I added.

it works good now for me

### CODE REVIEW

**Comment by scipilot** [comment]
Hi, I also found this problem and would like this fix.

Is there a reason this hasn't been merged in yet? (I can see travis is failing but it say's it can be merged)

update: I can see in the test build results, the new 'card' required parameter is causing dependencies to break. @funju47shin Were you going to address these dependencies? thanks

**Comment by greydnls** [comment]
@scipilot The tests need to pass for me to be able to merge. @funju47shin are you able to update tests so the build passes? 

I'd be happy to merge, after that.

**Comment by scipilot** [comment]
@kayladnls thanks for the reply, I understand. I'll try to replicate and check what @funju47shin has done next week - I might be able to address the problems myself. (However I do currently have workarounds in place, for this and pull/1 too, so it's less urgent).

**Comment by delatbabel** [comment]
I'm assuming that this is superseded by #10 -- if not then someone needs to resubmit with a working PR.

**Pull request closed without merging**
