### PR TITLE
Prepare for v3 Release

### PR DESCRIPTION
**Pull request by sudiptpa**

### CODE REVIEW

**Comment by sudiptpa** [comment]
@Orteko having the expiryMonth as 12 should fix it. Changed all of them and tests are still green.

**Comment by sudiptpa** [comment]
@delatbabel and @barryvdh  review this PR for v3 release.

**Comment by barryvdh** [comment]
Thanks!

**Comment by sudiptpa** [comment]
@barryvdh any chances to tag a new v3.0.0 release soon ?

**Comment by barryvdh** [comment]
Done

**Comment by sudiptpa** [comment]
Thanks but should it be  v3.0.0 or  V3.0.0 ?

**Comment by barryvdh** [comment]
Does it matter?

**Comment by sudiptpa** [comment]
Not sure exactly but, i see people doing v3.0.0 normally.

**Comment by sudiptpa** [comment]
No problem that all works, just tested.

**Pull request merged**
