### PR TITLE
Update DirectPostAuthorizeResponse.php

### PR DESCRIPTION
**Pull request by funju47shin**
when I check out this payment system, it shows me error like this

'This response does not support redirection.'

so if I implement RedirectResponseInterface, it redirects properly

### CODE REVIEW

**Comment by jason-zz** [comment]
I have the same problem. 
@funju47shin this solution works. Are you able to update the code to pass the test ?
Adding blank line after 'use Omnipay\Common\Message\RedirectResponseInterface;' should fix issue for test.

**Comment by timeverts** [comment]
@funju47shin, please get this solution integrated as soon as possible as I also have the same problem which could be addressed by your solution.

**Comment by delatbabel** [comment]
This still fails travis testing despite the recent fix. I can't merge until the travis tests pass.

**Comment by delatbabel** [comment]
I'm assuming that this is invalidated by #10

**Pull request closed without merging**
